

name: Deploy to Amazon ECS

on:
  push:
    branches: [ "master" ]

- uses: wangsijie/static-deploy-tool@v1
  with:
    oss-ak: ${{ secrets.OSS_AK }}
    oss-sk: ${{ secrets.OSS_SK }}
    oss-region: ${{ secrets.OSS_REGION }}
    oss-bucket: ${{ secrets.OSS_BUCKET }}
    oss-endpoint: oss-accelerate.aliyuncs.com
    local-path: __tests__/files
    remote-path: static-deploy-tool-test/action-sync
