name: Deploy to Ali OSS

on:
    push:
      branches:
          - develop

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install
              run: npm ci

            - name: Build
              run: |
                  version=$(node -p "require('./package.json').version")
                  REACT_APP_VERSION=$version npm run build

            - name: Install static-deploy-tool
              run: npm i -g static-deploy-tool

            - name: Sync
              run: static-deploy-tool sync "build" "static-deploy-tool-test/action-sync"
              env:
                  OSS_AK: ${{ secrets.OSS_AK }}
                  OSS_SK: ${{ secrets.OSS_SK }}
                  OSS_REGION: ${{ vars.OSS_REGION }}
                  OSS_BUCKET: ${{ vars.OSS_BUCKET }}
                  OSS_ENDPOINT: oss-accelerate.aliyuncs.com
