name: Deploy

env:
    ALICLOUD_ACCESS_KEY_ID: ${{secrets.ALICLOUD_ACCESS_KEY_ID}}
    ALICLOUD_ACCESS_KEY_SECRET: ${{secrets.ALICLOUD_ACCESS_KEY_SECRET}}
    ALICLOUD_REGION_ID: ${{vars.ALICLOUD_REGION_ID}}

on:
    push:
      branches:
          - develop

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install application
              run: npm ci

            - name: Build application
              run: |
                  version=$(node -p "require('./package.json').version")
                  REACT_APP_VERSION=$version npm run build

            - name: Install CLI
              run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/aliyun/aliyun-cli/HEAD/install.sh)"

            - name: Upload build
              run: aliyun oss cp ./build oss://yt-germ-bucket/ -r -u
