name: Deploy to Ali OSS

on:
    push:
      branches:
          - develop

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install
              run: npm ci

            - name: Build application
              run: |
                  version=$(node -p "require('./package.json').version")
                  REACT_APP_VERSION=$version npm run build

            - name: Upload files via CLI
              uses: jerray/setup-aliyun-cli-action@v1.0.0
              with:
                aliyun-cli-version: '3.0.165'
                mode: AK
                access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
                access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
                region: ${{ vars.OSS_REGION }}
              run: aliyun oss cp ./build oss://yt-germ-bucket -r -u
