name: Deploy to Ali OSS

on:
    push:
      branches:
          - develop

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Version
              run: git describe --always >> "$npm_package_version"

            - name: Build
              run: npm run build

            - name: Install static-deploy-tool
              shell: bash
              run: npm i -g static-deploy-tool

            - name: Sync
              shell: bash
              run: static-deploy-tool sync "build" "static-deploy-tool-test/action-sync"
              env:
                  OSS_AK: ${{ secrets.OSS_AK }}
                  OSS_SK: ${{ secrets.OSS_SK }}
                  OSS_REGION: ${{ secrets.OSS_REGION }}
                  OSS_BUCKET: ${{ secrets.OSS_BUCKET }}
                  OSS_ENDPOINT: oss-accelerate.aliyuncs.com
